<!DOCTYPE html>
<html lang="en-US" >
<head>
<meta charset="UTF-8">
<#assign ctx = request.contextPath />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link type="text/css" media="all" href="${ctx!}/assets-web/css/index.css" rel="stylesheet" />
<title>login</title>
<link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon-precomposed" href="apple-touch-icon.png">
<link rel='stylesheet' id='font-awesome-css' href="${ctx!}/assets-web/css/font-awesome-4.4.0/css/font-awesome.min.css" type='text/css' media='all' />
<script type='text/javascript' src='${ctx!}/assets-web/css/js/jquery-1.10.2.min.js'></script>
<script src="${ctx!}/assets/js/jquery-validate/jquery.validate.min.js"></script>
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv-printshiv.min.js?ver=4.3.1'></script> <![endif]-->
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js?ver=4.3.1'></script> 
<![endif]-->

<meta name="generator">
</head>
<script type="text/javascript">
	$(document).ready(function() {
		 $("form#resetForm").validate({
		     errorElement: "div",
             errorClass:"err-tip",
		     rules: {
		        account: {
		           required: true,
				   email: true,
				   remote: {
	                    type: "post",
	                    url: "${ctx!}/register/isExist.do",
	                    data: {
	                        account: function() {
	                            return $("#account").val();
	                        }
	                    },
				  }
		        }
		     },
		     messages: {
				account: {
					required: "Please enter your email address",
	                email: "Mailbox format error",
	                remote: "Mailbox not registered"
				},
			},
			submitHandler: function(form) {
        	$.ajax({
                url: $("#resetForm").attr("action"),
                type: "POST",
                data: {
                    account: $("#account").val(),
                },
                dataType: "json",
                cache: false,
                beforeSend: function() {
                    $('#sub-reset-password').attr("disabled", true);
                    $("#loading_hint").show();
                    $("#hint").text("Being sent...");
                },
                complete: function(message) {
                	$("#loading_hint").hide();
                    $("#sub-reset-password").attr("disabled", false);
                    var result = eval("(" + message.responseText + ")");
                    if (result.success) {
					   $(".alert-error").hide();
					   $("#alert").addClass("alert-success");
					   $("#alert").text(result.message);
                       $("#alert").show();
					 } else {  
					   $(".alert-error").hide();
					   $("#alert").addClass("alert-error");
					   $("#alert").html(result.message);
                       $("#alert").show();
		             }   
                }
            });
        }
		 });
	}); 
</script>
<body class="blog">
<section id="div_bg" >
	<div class="login-wrapper">
      <div class="login-container"> 
        <a href="/" title="back home" class="logo"></a>
        <div class="signup-forms">
          <div class="signup-box" >
            <div class="add-info">
              <form action="send_resetemail.do" method="post" id="resetForm">
                <div class="form-field">
                  <input name="account" id="account" type="text" placeholder="Email Address" autocomplete="off"  class="login-email" value="">
                </div>
                <div class="submit-btn">
                  <button type="submit">Password Retrieve</button>
                </div>
                <div class="form-bottom">
                    <a href="${ctx!}/login.htm" class="form-field-a right">Already got an account? Sign in here</a>
                    <div class="clear"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
<!-- Dynamic page generated in 0.606 seconds. --> 
<!-- Cached page generated by WP-Super-Cache on 2015-11-09 15:27:54 --> 

<!-- Compression = gzip -->
</body>
<script type="text/javascript">

function againActivate () {
	$.ajax({
        url:  "${ctx}/register/again_activate.do",
        type: "GET",
        data: {account: $("#account").val()},
        dataType: "json",
        cache: false,
        beforeSend: function() {
            $('#sub-login').attr("disabled", true);
            $("#loading_hint").show();
            $("#hint").text("Being sent...");
        },
        success: function(data) {
        	$("#loading_hint").hide();
        	$("#loading_hint").show();
        	$("#hint").text("Send success...");
        	setTimeout(function(){
       		   $("#loading_hint").hide();
      	    },1500);
            $('#sub-login').attr("disabled", false);
        }
    });
}
</script>

</html>