package com.wenjing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wenjing.entity.BlogTagAssociation;

public interface BlogTagAssociationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insert(BlogTagAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insertSelective(BlogTagAssociation record);
    
    /**
     * 批量插入
     * 
     * @param blogTagAssociationList
     * @return
     */
    int insertBatch(@Param("blogTagAssociationList")List<BlogTagAssociation> blogTagAssociationList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    BlogTagAssociation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKeySelective(BlogTagAssociation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtagassociation
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKey(BlogTagAssociation record);
    
    /**
     * 
     * @param blogIds
     * @return
     */
    int deleteByBlogIds(@Param("blogIds")String[] blogIds);
}