package com.wenjing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wenjing.entity.BlogCategory;

public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    BlogCategory selectByPrimaryKey(String id);
    
    /**
     * 
     * @param id
     * @return
     */
    BlogCategory selectWithPageById(String id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKey(BlogCategory record);
    
    /**
     * 更改博客种类里的博客数量
     */
    void changeBlogNumberById(@Param("changeValue")Integer changeValue,@Param("id")String id);
    
    
    /**
     * 更新博客种类的生成状态
     * 
     * @param isCreate
     * @param id
     */
    void updateIsCreateById(@Param("isCreate")int isCreate,@Param("id")String id);
    
    /**
     * 查出所有的博客类型列表
     * 
     * @return
     */
    List<BlogCategory> findAll();
    
    /**
     * 查询所有显示的种类信息
     * 
     * @return
     */
    List<BlogCategory> findAllShowCategory();
}