package com.wenjing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wenjing.entity.BlogTag;

public interface BlogTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insert(BlogTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insertSelective(BlogTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    BlogTag selectByPrimaryKey(String id);
    
    BlogTag selectWithPageById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKeySelective(BlogTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogtag
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int updateByPrimaryKey(BlogTag record);
    
    /**
     * 更新博客标签页面的生成状态
     * @param isCreate
     * @param id
     */
    void updateIsCreateById(@Param("isCreate")int isCreate,@Param("id")String id);
    
    /**
     * 查询所有的博客标签
     * 
     * @return
     */
    List<BlogTag> findAll();
    
    /**
     * 查询所有显示的标签
     * 
     * @return
     */
    List<BlogTag> findAllShow();
    
    
    /**
     * 根据博客ID查询博客标签
     * 
     * @return
     */
    List<BlogTag> findByBlogId(String blogId);
}