package com.wenjing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wenjing.entity.CommentsToBlog;


public interface CommentsToBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentstocategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insert(CommentsToBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentstocategory
     *
     * @mbggenerated Fri Oct 30 16:05:23 CST 2015
     */
    int insertSelective(CommentsToBlog record);
    
    /**
     * 计算总数量
     * @return
     */
    int countAllByCondition(@Param("blogName")String blogName,@Param("status")Integer status);
    
    /**
     * 根据blogId查询评论的总条数
     * @param blogId
     * @return
     */
    int countAllByBlogId(String blogId);
    
    /**
     * 查询博客下子评论的数量
     */
    int countChildrenCommentsNumber(String blogId);
    
    /**
     * 根据Id查询评论信息所关联的所有内容
     * 
     * @param id
     * @return
     */
    CommentsToBlog findAllInformationById(String id);
    
    /**
     * 分页查询
     * 
     * @param start
     * @return
     */
    List<CommentsToBlog> findByPage(@Param("start")int start,@Param("size")int size,@Param("blogName")String blogName,@Param("status")Integer status);
    
    /**
     * 根据blogId和分页信息查询博客评论
     * 
     * @return
     */
    List<CommentsToBlog> findPages(@Param("blogId")String blogId,@Param("start")int start,@Param("size")int size);
    
    /**
     * 根据Id设置是否显示
     */
    void changeIsShow(@Param("id")String id,@Param("isShow")Integer isShow);
    
    List<String> findChildrenId(String id);
    
    void deleteById(String id);
    
    void updateIsShowAndStatus(@Param("id")String id,@Param("isShow")int isShow,@Param("status")int status);
    
    int findLevel(String id);
    
    /**
     * 根据parentId查询所有的子评论
     * 
     * @return
     */
    List<CommentsToBlog> findByParentId(String id);
}