<!DOCTYPE html>
<html lang="en-US" >
<head>
<meta charset="UTF-8">
<#assign ctx = request.contextPath />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link type="text/css" media="all" href="${ctx!}/assets-web/css/index.css" rel="stylesheet" />
<title>login</title>
<link rel="shortcut icon" href="${ctx!}/favicon.ico">
<link rel="apple-touch-icon-precomposed" href="${ctx!}/apple-touch-icon.png">
<link rel='stylesheet' id='font-awesome-css' href="${ctx!}/assets-web/css/font-awesome-4.4.0/css/font-awesome.min.css" type='text/css' media='all' />
<script type='text/javascript' src='${ctx!}/assets-web/js/jquery-1.10.2.min.js'></script>
<script src="${ctx!}/assets/js/jquery-validate/jquery.validate.min.js"></script>
<!-- 密钥 -->
<script type="text/javascript" src="${ctx!}/assets/js/key/rsa.js"></script>
<script type="text/javascript" src="${ctx!}/assets/js/key/base64.js"></script> 
<script type="text/javascript" src="${ctx!}/assets/js/key/jsbn.js"></script> 
<script type="text/javascript" src="${ctx!}/assets/js/key/prng4.js"></script> 
<script type="text/javascript" src="${ctx!}/assets/js/key/rng.js"></script> 
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv-printshiv.min.js?ver=4.3.1'></script> <![endif]-->
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js?ver=4.3.1'></script> 
<![endif]-->

<meta name="generator">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-38017454-1', 'auto');
  ga('send', 'pageview');

</script>
<body class="blog">
<section id="div_bg" >
	<div class="login-wrapper">
      <div class="login-container"> 
        <a href="/" title="Back Home" class="logo"></a>
        <div class="signup-forms">
          <div class="signup-box" >
            <div class="add-info">
              <form action="login/submit.do" method="post" id="loginForm">
                <div class="form-field">
                  <input name="account" id ="account" type="text" placeholder="Email Address" autocomplete="off"  class="login-email" value="">
                </div>
                <div class="form-field">
                  <input name="password" id="password" type="password" placeholder="Password" autocomplete="off"  class="login-password" value="">
                </div>
                <div class="form-field">
                  <div class="">
                   <input name="captcha" id="captcha" type="text" placeholder="Verification Code" autocomplete="off" class="form-field-CAPTCHA">
                   <a href="" class="vcode-send">
                    <img src="captcha.do?d='+new Date().getTime()" title="" onclick="this.src='captcha.do?d='+new Date().getTime()" class="yzm-img" style="width:120px;height:46px;">
                   </a>
                   <div class="clear"></div>
                  </div>
                </div>
                <div class="submit-btn">
                  <button type="submit">Sign in to your account</button>
                </div>
                <div class="form-bottom">
                	<a href="${ctx!}/password/reset_email.htm" class="form-field-a left">Forget Password</a>
                    <a href="${ctx!}/register.htm" class="form-field-a right">Create Account</a>
                    <div class="clear"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>


<!-- Dynamic page generated in 0.606 seconds. --> 
<!-- Cached page generated by WP-Super-Cache on 2015-11-09 15:27:54 --> 

<!-- Compression = gzip -->
</body>
<script type="text/javascript">

$(".add-info-ul li").click(function () {
        $(".add-info-ul li").removeClass("add-info-ul-select");
        $(this).addClass("add-info-ul-select");
        $(".add-info-ul li").find(".add-info-ul-select .adddown").hide();
        $(this).find(".add-info-ul-select .adddown").show();
        var Index = $(this).index();
        $(".denglu").hide();
        $(".denglu:eq(" + Index + ")").show();
    })
    
jQuery(document).ready(function($) {
    <#if orderError??>
       alert("${orderError}");
    </#if>
    //用户登录
    $("form#loginForm").validate({
        errorElement: "div",
        errorClass:"err-tip",
        rules: {
            account: {
                required: true,
                email: true,
                remote: {
                    type: "post",
                    url: "${ctx!}/register/isExist.do",
                    data: {
                        account: function() {
                            return $("#account").val();
                        }
                    },
                }
            },
            password: {
                required: true,
            },
            captcha: {
                required: true,
                remote: {
                    type: "post",
                    url: "${ctx!}/register/isCaptcha.do",
                    data: {
                        captcha: function() {
                            return $("#captcha").val();
                        }
                    },
                }
            },
        },
        messages: {
            account: {
                required: "Enter your email address",
                email: "Invalid email format",
                remote: "User name already exists"
            },
            password: {
                required: "Enter confirm password"
            },
            captcha: {
                required: "Enter verification code",
                remote: "Wrong verification code"
            },
        },
        submitHandler: function(form) {
            $.ajax({
                url: "${ctx!}/common/public_key.do",
                type: "GET",
                dataType: "json",
                cache: false,
                beforeSend: function() {
                    $('#sub-login').attr("disabled", true);
                    $("#loading_hint").show();
                    $("#hint").text("login...");
                },
                success: function(data) {
                    var rsaKey = new RSAKey();
                    rsaKey.setPublic(b64tohex(data.modulus), b64tohex(data.exponent));
                    var enPassword = hex2b64(rsaKey.encrypt($("#password").val()));
                    $.ajax({
                        url: $("#loginForm").attr("action"),
                        type: "POST",
                        data: {
                            account: $("#account").val(),
                            enPassword: enPassword,
                        },
                        dataType: "json",
                        cache: false,
                        complete: function(message) {
                            $("#loading_hint").hide();
                            $('#sub-login').attr("disabled", false);
                            var result = eval("(" + message.responseText + ")");
                            if (result.success) {
                                <#if redirectUrl??>
                                   location.href = "${(redirectUrl)!}"; 
                                <#else> 
                                   location.href = "${ctx!}/"; 
                                 </#if>
					         } else {  
					             $("#error-pass").html(result.message);
					           }   
							}
						});
					}
				});
			}
		});
		
		// 非注册用户订单查询
		 $("form#unregisteredOrderForm").validate({
		       errorElement: "div",
               errorClass:"err-tip",
			  rules: {
			     non_user_account:{
	                required: true,
	                email: true,
	            },
	            non_user_orderNo:{
	                required: true,
	                remote: {
	                    type: "post",
	                    url: "${ctx!}/login/isOrderNo.do",
	                    data: {
	                        orderNo: function() {
	                            return $("#non_user_orderNo").val();
	                         }
	                       },
	                   }
	                }
	            },
	          messages: {
	              non_user_account: {
                      required: "Enter your email address",
                      email: "Invalid email format"
	            },
	              non_user_orderNo: {
	                required: "请输入您的订单号",
	                remote: "该订单号不存在",
	            },
			 },
			 submitHandler: function(form) {
               form.submit();
			}
		 });
});
function againActivate () {
	$.ajax({
        url:  "${ctx}/register/again_activate.do",
        type: "GET",
        data: {account: $("#account").val()},
        dataType: "json",
        cache: false,
        beforeSend: function() {
            $('#sub-login').attr("disabled", true);
            $("#loading_hint").show();
            $("#hint").text("Sending...");
        },
        success: function(data) {
        	$("#loading_hint").hide();
        	$("#loading_hint").show();
        	$("#hint").text("Send Successful...");
        	setTimeout(function(){
       		   $("#loading_hint").hide();
      	    },1500);
            $('#sub-login').attr("disabled", false);
        }
    });
}
</script > 
</html>