<!DOCTYPE html>
<html lang="en-US" >
<head>
<meta charset="UTF-8">
<#assign ctx = request.contextPath />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link type="text/css" media="all" href="${ctx!}/assets-web/css/index-min.css" rel="stylesheet" />
<meta name="keywords" content="${(page.metakeywords)!}" />
<meta name="description" content="${(page.metadescription)!}"/>
<title>${(page.metatitle)!}</title>
<link rel="shortcut icon" href="${ctx!}/favicon.ico">
<link rel="apple-touch-icon-precomposed" href="${ctx!}/apple-touch-icon.png">
<link rel='stylesheet' id='font-awesome-css' href="${ctx!}/assets-web/css/fonts/linecons/css/linecons-min.css" type='text/css' media='all' />
<link rel='stylesheet' id='font-awesome-css' href="${ctx!}/assets-web/css/font-awesome-4.4.0/css/font-awesome.min.css" type='text/css' media='all' />
<link rel='stylesheet' id='google-font-css'  href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic|Cabin:600,600italic,400,400italic,700,700italic&#038;subset=latin,latin-ext' type='text/css' media='all' />
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv-printshiv.min.js?ver=4.3.1'></script> <![endif]-->
<!--[if lt IE 9]> 
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js?ver=4.3.1'></script> 
<![endif]-->

<meta name="generator">
<style id="fit-vids-style">
.fluid-width-video-wrapper { width: 100%; position: relative; padding: 0; }
.fluid-width-video-wrapper iframe, .fluid-width-video-wrapper object, .fluid-width-video-wrapper embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }
</style>
<style id="ShrinkMenu">
.menu-shrink { top : -49px !important; }
</style>
</head>
<body class="blog">
<div id="top"></div>
<#include "/front/include/top.ftl"/>
<section class="hero small-hero" style="background-image: url(${ctx!}/assets-web/images/aboutus-bg.jpg) ;color: #fff;position: relative;background-color:#6c6e73;background-position: center;background-size: cover;background-repeat: no-repeat;">
  <div class="bg-overlay">
    <div class="container" style="">
      <div class="breadcrumbs">
          <ul>
              <li><a href="${ctx!}/">Home</a></li>
              <li><a href="">About us</a></li>
          </ul>
      </div>
      <div class="list-intro-wrap">
        <h1 class="intro-title" style="text-align:center; margin-top:0;">ABOUT US</h1>
      </div>
    </div>
  </div>
</section>

<section class="featured-destinations" style="background-color:#f5f6f6;">
  <div class="container">
    <div class="text-warp" style="margin:40px 0;">
    	<h1 class="text-h1">About Us</h1>
        <p>Welcome to InterTrips, an Online Travel Agency specializing in Asia and beyond. Since 2002, InterTrips has been committed to bring the best of sceneries of the world to customers’ doorsteps. We are passionate travelers, enthusiastic about showing the world and present the most authentic travel experiences for our customers. </p>
        <p>When you are booking and travelling with InterTrips, you are choosing a strong, reliable tour operator with a commitment to providing the best quality travel packages. We know Asia through our 15 years of experience, featuring a high level expertise with regards to Asia attractions, food, hotels, excursions, cruises, and whatever other request our customers may have. </p>
        <p>Choose from our first class tour packages including independent travel itineraries(FITs), customized individual and group travel, coach bus escorted tours, locally hosted leisure packages, and river & ocean cruise packages all around Asia.</p>
        <p>Book with InterTrips today to see what InterTrips can offer. Along the way, InterTrips is at your service.</p>
    </div>
  </div>
</section>
<#--bottom-->
	<#include "/front/include/bottom.ftl"/>
<#--bottom-->
<script type="text/javascript">
if (typeof jQuery.fn.fitVids === "undefined") { document.write("<script src='${ctx!}/assets-web/js/jquery.fitvids.min.js'>\x3C/script>"); }


</script> 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-38017454-1', 'auto');
  ga('send', 'pageview');

</script>
<script type="text/javascript">
$(function(){
	$('input').customInput();
});
</script>
<!-- Dynamic page generated in 0.606 seconds. --> 
<!-- Cached page generated by WP-Super-Cache on 2015-11-09 15:27:54 --> 

<!-- Compression = gzip -->
</body>
</html>